### ISSUE TITLE
Player was booted: Invalid operation at this state.

### ISSUE THREAD

**Issue by FrostBird347** [popstarfreas/Dimensions#57] opened 2020-01-04 02:41 UTC
Whenever I attempt to join a vanilla server both with and without a password the player gets kicked with this message.

**Comment by popstarfreas** [comment] 2020-01-04 13:51
This is because dimensions tries to send the real ip address of a client using an unused packet.

Be aware that if you want to be able to use Dimensions with a vanilla server, you will not be able to ban players by IP address. I can add an option to allow use with vanilla servers, but this is the downside.

**Comment by FrostBird347** [comment] 2020-01-04 14:22
Thanks, IP banning should not be an issue for me because I am running a private server. Although, a possible solution to that is to ban players through the proxy itself.

**Comment by popstarfreas** [comment] 2020-01-06 19:55
In progress at: https://github.com/popstarfreas/Dimensions/pull/58
You can try the build there and see if that works yet. You just need to set isVanilla: true on a server in the config, check the config.js.example for where this new property is.

**Comment by FrostBird347** [comment] 2020-01-07 01:48
I set isVanilla: true on the server config and was able to connect to a vanilla server, but whenever I tried to switch to another vanilla server, it would fail with the same message, resulting in my player being unable to connect to any server while still seeing the old terrain of the previous world.

**Comment by popstarfreas** [comment] 2020-02-02 21:57
Sorry about the lack of activity. I'll try to look at this again soon.

**Comment by F-fengzi** [comment] 2022-04-24 04:06
Still this issue on vanilla (without plugins), please look over this issue if possible

**Comment by popstarfreas** [comment] 2022-04-24 15:10
This was added in 9e3d59244fd374d58c97a5004af9c3ba83f61041 and will be in the next release. I could not reproduce the issue that FrostBird347 mentioned, so it's possible they put in the wrong currentTerrariaVersion, which now does not exist in 6b6e3a40725af4ff02fdfadea8e337a2879c8f25 so this shouldn't be a problem now.

**Closed** 2022-04-24 16:24 UTC
Labels: enhancement
